/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SiteInternetPlombierRouteImport } from './routes/site-internet-plombier'
import { Route as SiteInternetMenuisierRouteImport } from './routes/site-internet-menuisier'
import { Route as SiteInternetElectricienRouteImport } from './routes/site-internet-electricien'
import { Route as SiteInternetCouvreurRouteImport } from './routes/site-internet-couvreur'
import { Route as SitalyAppRouteImport } from './routes/sitaly-app'
import { Route as PolitiqueConfidentialiteRouteImport } from './routes/politique-confidentialite'
import { Route as MentionsLegalesRouteImport } from './routes/mentions-legales'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as CgvRouteImport } from './routes/cgv'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteInternetPlombierRoute = SiteInternetPlombierRouteImport.update({
  id: '/site-internet-plombier',
  path: '/site-internet-plombier',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteInternetMenuisierRoute = SiteInternetMenuisierRouteImport.update({
  id: '/site-internet-menuisier',
  path: '/site-internet-menuisier',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteInternetElectricienRoute = SiteInternetElectricienRouteImport.update({
  id: '/site-internet-electricien',
  path: '/site-internet-electricien',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteInternetCouvreurRoute = SiteInternetCouvreurRouteImport.update({
  id: '/site-internet-couvreur',
  path: '/site-internet-couvreur',
  getParentRoute: () => rootRouteImport,
} as any)
const SitalyAppRoute = SitalyAppRouteImport.update({
  id: '/sitaly-app',
  path: '/sitaly-app',
  getParentRoute: () => rootRouteImport,
} as any)
const PolitiqueConfidentialiteRoute =
  PolitiqueConfidentialiteRouteImport.update({
    id: '/politique-confidentialite',
    path: '/politique-confidentialite',
    getParentRoute: () => rootRouteImport,
  } as any)
const MentionsLegalesRoute = MentionsLegalesRouteImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const CgvRoute = CgvRouteImport.update({
  id: '/cgv',
  path: '/cgv',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteWithChildren
  '/cgv': typeof CgvRoute
  '/cookies': typeof CookiesRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/politique-confidentialite': typeof PolitiqueConfidentialiteRoute
  '/sitaly-app': typeof SitalyAppRoute
  '/site-internet-couvreur': typeof SiteInternetCouvreurRoute
  '/site-internet-electricien': typeof SiteInternetElectricienRoute
  '/site-internet-menuisier': typeof SiteInternetMenuisierRoute
  '/site-internet-plombier': typeof SiteInternetPlombierRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cgv': typeof CgvRoute
  '/cookies': typeof CookiesRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/politique-confidentialite': typeof PolitiqueConfidentialiteRoute
  '/sitaly-app': typeof SitalyAppRoute
  '/site-internet-couvreur': typeof SiteInternetCouvreurRoute
  '/site-internet-electricien': typeof SiteInternetElectricienRoute
  '/site-internet-menuisier': typeof SiteInternetMenuisierRoute
  '/site-internet-plombier': typeof SiteInternetPlombierRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog': typeof BlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteWithChildren
  '/cgv': typeof CgvRoute
  '/cookies': typeof CookiesRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/politique-confidentialite': typeof PolitiqueConfidentialiteRoute
  '/sitaly-app': typeof SitalyAppRoute
  '/site-internet-couvreur': typeof SiteInternetCouvreurRoute
  '/site-internet-electricien': typeof SiteInternetElectricienRoute
  '/site-internet-menuisier': typeof SiteInternetMenuisierRoute
  '/site-internet-plombier': typeof SiteInternetPlombierRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blog'
    | '/cgv'
    | '/cookies'
    | '/mentions-legales'
    | '/politique-confidentialite'
    | '/sitaly-app'
    | '/site-internet-couvreur'
    | '/site-internet-electricien'
    | '/site-internet-menuisier'
    | '/site-internet-plombier'
    | '/sitemap.xml'
    | '/blog/$slug'
    | '/blog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cgv'
    | '/cookies'
    | '/mentions-legales'
    | '/politique-confidentialite'
    | '/sitaly-app'
    | '/site-internet-couvreur'
    | '/site-internet-electricien'
    | '/site-internet-menuisier'
    | '/site-internet-plombier'
    | '/sitemap.xml'
    | '/blog/$slug'
    | '/blog'
  id:
    | '__root__'
    | '/'
    | '/blog'
    | '/cgv'
    | '/cookies'
    | '/mentions-legales'
    | '/politique-confidentialite'
    | '/sitaly-app'
    | '/site-internet-couvreur'
    | '/site-internet-electricien'
    | '/site-internet-menuisier'
    | '/site-internet-plombier'
    | '/sitemap.xml'
    | '/blog/$slug'
    | '/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogRoute: typeof BlogRouteWithChildren
  CgvRoute: typeof CgvRoute
  CookiesRoute: typeof CookiesRoute
  MentionsLegalesRoute: typeof MentionsLegalesRoute
  PolitiqueConfidentialiteRoute: typeof PolitiqueConfidentialiteRoute
  SitalyAppRoute: typeof SitalyAppRoute
  SiteInternetCouvreurRoute: typeof SiteInternetCouvreurRoute
  SiteInternetElectricienRoute: typeof SiteInternetElectricienRoute
  SiteInternetMenuisierRoute: typeof SiteInternetMenuisierRoute
  SiteInternetPlombierRoute: typeof SiteInternetPlombierRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/site-internet-plombier': {
      id: '/site-internet-plombier'
      path: '/site-internet-plombier'
      fullPath: '/site-internet-plombier'
      preLoaderRoute: typeof SiteInternetPlombierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/site-internet-menuisier': {
      id: '/site-internet-menuisier'
      path: '/site-internet-menuisier'
      fullPath: '/site-internet-menuisier'
      preLoaderRoute: typeof SiteInternetMenuisierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/site-internet-electricien': {
      id: '/site-internet-electricien'
      path: '/site-internet-electricien'
      fullPath: '/site-internet-electricien'
      preLoaderRoute: typeof SiteInternetElectricienRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/site-internet-couvreur': {
      id: '/site-internet-couvreur'
      path: '/site-internet-couvreur'
      fullPath: '/site-internet-couvreur'
      preLoaderRoute: typeof SiteInternetCouvreurRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitaly-app': {
      id: '/sitaly-app'
      path: '/sitaly-app'
      fullPath: '/sitaly-app'
      preLoaderRoute: typeof SitalyAppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politique-confidentialite': {
      id: '/politique-confidentialite'
      path: '/politique-confidentialite'
      fullPath: '/politique-confidentialite'
      preLoaderRoute: typeof PolitiqueConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentions-legales': {
      id: '/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/mentions-legales'
      preLoaderRoute: typeof MentionsLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cgv': {
      id: '/cgv'
      path: '/cgv'
      fullPath: '/cgv'
      preLoaderRoute: typeof CgvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogRoute: BlogRouteWithChildren,
  CgvRoute: CgvRoute,
  CookiesRoute: CookiesRoute,
  MentionsLegalesRoute: MentionsLegalesRoute,
  PolitiqueConfidentialiteRoute: PolitiqueConfidentialiteRoute,
  SitalyAppRoute: SitalyAppRoute,
  SiteInternetCouvreurRoute: SiteInternetCouvreurRoute,
  SiteInternetElectricienRoute: SiteInternetElectricienRoute,
  SiteInternetMenuisierRoute: SiteInternetMenuisierRoute,
  SiteInternetPlombierRoute: SiteInternetPlombierRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
